# fly.toml app configuration file generated for personal-cms on 2023-06-04T19:05:00-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "personal-cms"
primary_region = "ord"

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
